In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv('input/PD 2022 Wk 1 Input - Input.csv')

# Removing any unnecessary fields (parental fields) will make this challenge easier to see what is happening at each step
df = df[['pupil first name', 'pupil last name', 'Date of Birth']]
df.head()

  pupil first name pupil last name Date of Birth
0            Ronna         Nellies    12/21/2013
1            Rusty       Andriulis     7/21/2012
2          Roberta       Oakeshott     12/4/2011
3             Lola       Rubinfajn     6/29/2012
4           Kamila        Benedtti     7/10/2012

In [2]:
# Format the pupil's name in First Name Last Name format
df['Pupil\'s Name'] = df['pupil first name'] + ' ' +df['pupil last name']

# Create the date for the pupil's birthday in calendar year 2022 (not academic year) 
df["This Year's Birthday"] = df['Date of Birth'].apply(lambda x : x[:-4] + '2021')

# Work out what day of the week the pupil's birthday falls on
# Remember if the birthday falls on a Saturday or Sunday, we need to change the weekday to Friday
df['Cake Needed On'] = df['This Year\'s Birthday'].astype('datetime64').dt.strftime('%A')
df['Cake Needed On'] = df['Cake Needed On'].apply(lambda x: 'Friday' if x == 'Saturday' or x == 'Sunday' else x)

# Work out what month the pupil's birthday falls within
df['Month'] = df['This Year\'s Birthday'].astype('datetime64').dt.strftime('%B')
df.head()

# Count how many birthdays there are on each weekday in each month
df['BDs per Weekday and Month'] = df.groupby(['Month','Cake Needed On'])['Pupil\'s Name'].transform('count')

# convert to csv file
cols = ['Pupil\'s Name', 'Date of Birth', 'This Year\'s Birthday', 'Month', 'Cake Needed On', 'BDs per Weekday and Month']
df.to_csv('output/output-2022-week02.csv', index=False, columns=cols)

In [3]:
output = pd.read_csv('output/output-2022-week02.csv')
output.head()

,Pupil's Name,Date of Birth,This Year's Birthday,Month,Cake Needed On,BDs per Weekday and Month
0,Ronna Nellies,12/21/2013,12/21/2021,December,Tuesday,9
1,Rusty Andriulis,7/21/2012,7/21/2021,July,Wednesday,12
2,Roberta Oakeshott,12/4/2011,12/4/2021,December,Friday,51
3,Lola Rubinfajn,6/29/2012,6/29/2021,June,Tuesday,15
4,Kamila Benedtti,7/10/2012,7/10/2021,July,Friday,46