In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_excel('input/Sample - Superstore.xls', sheet_name='Orders')

In [9]:
df.rename(columns=lambda x: x.replace(' ', '_'), inplace=True)

In [10]:
df.head()

,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,Country/Region,City,...,Postal_Code,Region,Product_ID,Category,Sub-Category,Product_Name,Sales,Quantity,Discount,Profit
0,1,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2020-152156,2020-11-08,2020-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2020-138688,2020-06-12,2020-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2019-108966,2019-10-11,2019-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [24]:
order = df[['Row_ID', 'Order_Date', 'Customer_ID']]

In [25]:
order.head()

   Row_ID Order_Date Customer_ID
0       1 2020-11-08    CG-12520
1       2 2020-11-08    CG-12520
2       3 2020-06-12    DV-13045
3       4 2019-10-11    SO-20335
4       5 2019-10-11    SO-20335

In [34]:
order['Year'] = order['Order_Date'].dt.year

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [35]:
order.head()

   Row_ID Order_Date Customer_ID  Year  Frist_Purchase
0       1 2020-11-08    CG-12520  2020             NaN
1       2 2020-11-08    CG-12520  2020             NaN
2       3 2020-06-12    DV-13045  2020             NaN
3       4 2019-10-11    SO-20335  2019             NaN
4       5 2019-10-11    SO-20335  2019             NaN

In [37]:
order['Frist_Purchase'] = order.groupby(by='Customer_ID')['Year'].transform('min')

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [39]:
order.head()

   Row_ID Order_Date Customer_ID  Year  Frist_Purchase
0       1 2020-11-08    CG-12520  2020            2019
1       2 2020-11-08    CG-12520  2020            2019
2       3 2020-06-12    DV-13045  2020            2020
3       4 2019-10-11    SO-20335  2019            2019
4       5 2019-10-11    SO-20335  2019            2019

In [44]:
order['Year'].drop_duplicates()

0     2020
3     2019
5     2018
12    2021
Name: Year, dtype: int64

In [53]:
for key, group in df.groupby('Customer_ID'):
    group['Frist_Purchase'].iloc[0]

KeyError: 'Frist_Purchase'